# Generated by Django 6.0.8 on 2026-08-04 17:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant_name', models.CharField(max_length=255, verbose_name='restaurant name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurant_logos/', verbose_name='logo')),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('phone', models.CharField(max_length=32, unique=True, verbose_name='phone number')),
                ('address', models.CharField(max_length=512, verbose_name='address')),
                ('city', models.CharField(max_length=128, verbose_name='city')),
                ('state', models.CharField(max_length=128, verbose_name='state')),
                ('country', models.CharField(max_length=128, verbose_name='country')),
                ('pincode', models.CharField(max_length=32, verbose_name='pincode')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('opening_time', models.TimeField(verbose_name='opening time')),
                ('closing_time', models.TimeField(verbose_name='closing time')),
                ('primary_color', models.CharField(default='#0d6efd', max_length=7, verbose_name='primary color')),
                ('secondary_color', models.CharField(default='#6c757d', max_length=7, verbose_name='secondary color')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'restaurant',
                'verbose_name_plural': 'restaurants',
                'ordering': ['restaurant_name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch_name', models.CharField(max_length=255, verbose_name='branch name')),
                ('address', models.CharField(max_length=512, verbose_name='address')),
                ('city', models.CharField(max_length=128, verbose_name='city')),
                ('state', models.CharField(max_length=128, verbose_name='state')),
                ('country', models.CharField(max_length=128, verbose_name='country')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='phone number')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='restaurants.restaurant', verbose_name='restaurant')),
            ],
            options={
                'verbose_name': 'branch',
                'verbose_name_plural': 'branches',
                'ordering': ['restaurant', 'branch_name'],
                'unique_together': {('restaurant', 'branch_name')},
            },
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table_number', models.CharField(max_length=32, verbose_name='table number')),
                ('qr_slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='QR slug')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='table_qr_codes/', verbose_name='QR image')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurants.branch', verbose_name='branch')),
            ],
            options={
                'verbose_name': 'table',
                'verbose_name_plural': 'tables',
                'ordering': ['branch', 'table_number'],
                'indexes': [models.Index(fields=['qr_slug'], name='restaurants_qr_slug_695056_idx'), models.Index(fields=['table_number'], name='restaurants_table_n_46898b_idx')],
                'unique_together': {('branch', 'table_number')},
            },
        ),
    ]
