# Generated by Django 6.0.8 on 2026-08-28 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_add_default_tap_reward'),
        ('restaurants', '0003_qrscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauranttable',
            name='reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tables', to='coupons.reward', verbose_name='reward'),
        ),
    ]
