# Generated by Django 6.0.8 on 2026-08-28 10:46

from django.db import migrations, models


def normalize_restaurant_countries(apps, schema_editor):
    Restaurant = apps.get_model('restaurants', 'Restaurant')
    uae_values = {'AE', 'UAE', 'UNITED ARAB EMIRATES'}
    for restaurant in Restaurant.objects.all().only('pk', 'country').iterator():
        normalized = (restaurant.country or '').strip().upper()
        country = 'AE' if normalized in uae_values else 'IN'
        Restaurant.objects.filter(pk=restaurant.pk).update(country=country)


def restore_country_names(apps, schema_editor):
    Restaurant = apps.get_model('restaurants', 'Restaurant')
    Restaurant.objects.filter(country='IN').update(country='India')
    Restaurant.objects.filter(country='AE').update(country='United Arab Emirates')


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restauranttable_reward'),
    ]

    operations = [
        migrations.RunPython(normalize_restaurant_countries, restore_country_names),
        migrations.AlterField(
            model_name='restaurant',
            name='country',
            field=models.CharField(choices=[('IN', 'India'), ('AE', 'United Arab Emirates')], default='IN', max_length=2, verbose_name='country'),
        ),
    ]
