# Generated by Django 6.0.8 on 2026-08-28 12:36

from django.db import migrations


def move_table_rewards_to_reward_configuration(apps, schema_editor):
    Gameplay = apps.get_model('games', 'Gameplay')
    RestaurantTable = apps.get_model('restaurants', 'RestaurantTable')
    database = schema_editor.connection.alias

    for table in RestaurantTable.objects.using(database).exclude(reward_id=None).iterator():
        table.reward.applicable_tables.add(table)

    for gameplay in Gameplay.objects.using(database).filter(
        assigned_reward_id=None,
        restaurant_table__reward_id__isnull=False,
    ).select_related('restaurant_table').iterator():
        gameplay.assigned_reward_id = gameplay.restaurant_table.reward_id
        gameplay.save(using=database, update_fields=['assigned_reward'])


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_reward_applicable_tables'),
        ('games', '0007_gameplay_assigned_reward'),
        ('restaurants', '0006_backfill_unconfigured_table_rewards'),
    ]

    operations = [
        migrations.RunPython(
            move_table_rewards_to_reward_configuration,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='restauranttable',
            name='reward',
        ),
    ]
