# Generated by Django 6.0.8 on 2026-08-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='full name')),
                ('phone_number', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='phone number')),
                ('whatsapp_number', models.CharField(blank=True, max_length=32, null=True, verbose_name='WhatsApp number')),
                ('total_visits', models.PositiveIntegerField(default=0, verbose_name='total visits')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'ordering': ['full_name'],
            },
        ),
    ]
