# Generated by Django 6.0.8 on 2026-08-04 17:17

import coupons.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('games', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('reward_type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('flat', 'Flat Discount'), ('free_item', 'Free Item'), ('bogo', 'Buy One Get One')], default='percentage', max_length=32, verbose_name='reward type')),
                ('reward_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='reward value')),
                ('minimum_score', models.PositiveIntegerField(default=0, verbose_name='minimum score')),
                ('valid_days', models.PositiveSmallIntegerField(default=1, verbose_name='valid days')),
                ('expiry_days', models.PositiveSmallIntegerField(default=30, verbose_name='expiry days')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='restaurants.restaurant', verbose_name='restaurant')),
            ],
            options={
                'verbose_name': 'reward',
                'verbose_name_plural': 'rewards',
                'ordering': ['restaurant', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon_code', models.CharField(default=coupons.models._generate_coupon_code, editable=False, max_length=32, unique=True, verbose_name='coupon code')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='coupon_qr_codes/', verbose_name='QR image')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='generated at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='customer.customer', verbose_name='customer')),
                ('gameplay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='games.gameplay', verbose_name='gameplay')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='restaurants.restaurant', verbose_name='restaurant')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='coupons.reward', verbose_name='reward')),
            ],
            options={
                'verbose_name': 'coupon',
                'verbose_name_plural': 'coupons',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reward',
            index=models.Index(fields=['restaurant', 'reward_type'], name='coupons_rew_restaur_c0fdce_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['coupon_code', 'generated_at'], name='coupons_cou_coupon__4ceb04_idx'),
        ),
    ]
