# Generated by Django 6.0.8 on 2026-08-05 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        ('customer', '0001_initial'),
        ('games', '0002_seed_games'),
        ('restaurants', '0003_qrscan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True, verbose_name='redeemed at')),
                ('device', models.CharField(blank=True, max_length=255, verbose_name='device')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
            ],
            options={
                'verbose_name': 'redemption',
                'verbose_name_plural': 'redemptions',
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.RemoveField(
            model_name='reward',
            name='expiry_days',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='valid_days',
        ),
        migrations.AddField(
            model_name='coupon',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='restaurants.branch', verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='expiry_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expiry at'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='qr_token',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='qr token'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='redemption_count',
            field=models.PositiveIntegerField(default=0, verbose_name='redemption count'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('redeemed', 'Redeemed')], default='pending', max_length=16, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='restaurants.restauranttable', verbose_name='table'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='valid from'),
        ),
        migrations.AddField(
            model_name='reward',
            name='coupon_valid_days',
            field=models.PositiveSmallIntegerField(default=7, verbose_name='coupon valid days'),
        ),
        migrations.AddField(
            model_name='reward',
            name='eligible_games',
            field=models.ManyToManyField(blank=True, related_name='eligible_rewards', to='games.game'),
        ),
        migrations.AddField(
            model_name='reward',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='reward',
            name='game_eligibility',
            field=models.CharField(choices=[('all', 'All Games'), ('specific', 'Specific Games')], default='all', max_length=16, verbose_name='game eligibility'),
        ),
        migrations.AddField(
            model_name='reward',
            name='max_daily_redemptions',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='max daily redemptions'),
        ),
        migrations.AddField(
            model_name='reward',
            name='max_total_redemptions',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='max total redemptions'),
        ),
        migrations.AddField(
            model_name='reward',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='reward_type',
            field=models.CharField(choices=[('percentage', 'Percentage Discount'), ('flat', 'Flat Discount'), ('free_item', 'Free Item'), ('bogo', 'Buy One Get One'), ('free_beverage', 'Free Beverage'), ('free_dessert', 'Free Dessert'), ('custom', 'Custom Reward')], default='percentage', max_length=32, verbose_name='reward type'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='reward_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='reward value'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['status'], name='coupons_cou_status_6345f0_idx'),
        ),
        migrations.AddField(
            model_name='redemption',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.branch'),
        ),
        migrations.AddField(
            model_name='redemption',
            name='coupon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='redemption', to='coupons.coupon'),
        ),
        migrations.AddField(
            model_name='redemption',
            name='redeemed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
