# Generated by Django 6.0.8 on 2026-08-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_add_default_tap_reward'),
        ('restaurants', '0006_backfill_unconfigured_table_rewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='applicable_tables',
            field=models.ManyToManyField(blank=True, related_name='applicable_rewards', to='restaurants.restauranttable', verbose_name='applicable tables'),
        ),
    ]
