"""
Django settings for playbite project.

Generated by 'django-admin startproject' using Django 6.0.8.
"""

import os
from pathlib import Path
from urllib.parse import urlparse

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# Security
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-replace-me-with-env')
DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() in {'1', 'true', 'yes'}
IS_RENDER = os.getenv('RENDER', 'False').lower() in {'1', 'true', 'yes'}
RENDER_EXTERNAL_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME', '').strip()
DATABASE_URL = os.getenv('DATABASE_URL', '').strip()
ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost 127.0.0.1').replace(',', ' ').split()
DEMO_MODE = os.getenv('DEMO_MODE', 'False').lower() in {'1', 'true', 'yes'}
PUBLIC_BASE_URL = (os.getenv('PUBLIC_BASE_URL') or os.getenv('SITE_URL') or '').strip().rstrip('/')
OWNER_ACCESS_PIN = os.getenv('OWNER_ACCESS_PIN', '8888').strip()
if len(OWNER_ACCESS_PIN) != 4 or not OWNER_ACCESS_PIN.isdigit():
    raise ImproperlyConfigured('OWNER_ACCESS_PIN must contain exactly four digits.')

if IS_RENDER:
    if SECRET_KEY == 'django-insecure-replace-me-with-env':
        raise ImproperlyConfigured('DJANGO_SECRET_KEY must be set on Render.')
    DEBUG = False
    ALLOWED_HOSTS += [RENDER_EXTERNAL_HOSTNAME] if RENDER_EXTERNAL_HOSTNAME else ['.onrender.com']

CSRF_TRUSTED_ORIGINS = os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS', '').replace(',', ' ').split()
if PUBLIC_BASE_URL:
    parsed_public_url = urlparse(PUBLIC_BASE_URL)
    if parsed_public_url.scheme == 'https' and parsed_public_url.netloc:
        CSRF_TRUSTED_ORIGINS.append(f'https://{parsed_public_url.netloc}')
elif RENDER_EXTERNAL_HOSTNAME:
    PUBLIC_BASE_URL = f'https://{RENDER_EXTERNAL_HOSTNAME}'
    CSRF_TRUSTED_ORIGINS.append(PUBLIC_BASE_URL)

if DEMO_MODE:
    # Cloudflare Quick Tunnel hostnames are random, so allow only that domain family.
    ALLOWED_HOSTS += ['.trycloudflare.com']
    CSRF_TRUSTED_ORIGINS += ['https://*.trycloudflare.com']
    # Cloudflare terminates HTTPS and forwards the original scheme in this header.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'marketing',
    'restaurants',
    'customer',
    'games',
    'coupons',
    'analytics_dashboard',
    'staff',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'playbite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'playbite.wsgi.application'

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=IS_RENDER,
        )
    }
else:
    # Local development keeps the existing on-disk SQLite workflow.
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'
LANGUAGES = [('en', 'English'), ('ar', 'العربية')]
LOCALE_PATHS = [BASE_DIR / 'locale']
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
}
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

SESSION_COOKIE_HTTPONLY = True
if IS_RENDER:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = int(os.getenv('DJANGO_SECURE_HSTS_SECONDS', '3600'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.User'
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'restaurants:dashboard'
LOGOUT_REDIRECT_URL = 'accounts:login'
EMAIL_BACKEND = os.getenv('DJANGO_EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
DEFAULT_FROM_EMAIL = os.getenv('DJANGO_DEFAULT_FROM_EMAIL', 'PlayBite <no-reply@playbite.local>')
