# Generated by Django 6.0.8 on 2026-08-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('staff', 'Staff'), ('super_admin', 'Super Admin')], default='owner', max_length=32, verbose_name='role'),
        ),
    ]
