# Generated by Django 6.0.8 on 2026-08-04 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=16, verbose_name='difficulty')),
                ('duration', models.DurationField(verbose_name='duration')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'game',
                'verbose_name_plural': 'games',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gameplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveIntegerField(default=0, verbose_name='score')),
                ('completed', models.BooleanField(default=False, verbose_name='completed')),
                ('play_time', models.DurationField(blank=True, null=True, verbose_name='play time')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('device', models.CharField(blank=True, max_length=255, verbose_name='device')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameplays', to='customer.customer', verbose_name='customer')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameplays', to='games.game', verbose_name='game')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameplays', to='restaurants.restaurant', verbose_name='restaurant')),
                ('restaurant_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gameplays', to='restaurants.restauranttable', verbose_name='restaurant table')),
            ],
            options={
                'verbose_name': 'gameplay',
                'verbose_name_plural': 'gameplays',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['restaurant', 'game'], name='games_gamep_restaur_28dfa5_idx'), models.Index(fields=['customer', 'created_at'], name='games_gamep_custome_4a4c76_idx')],
            },
        ),
    ]
