# Generated by Django 6.0.8 on 2026-08-28 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_reward_applicable_tables'),
        ('games', '0006_add_tap_at_ten'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplay',
            name='assigned_reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_gameplays', to='coupons.reward', verbose_name='assigned reward'),
        ),
    ]
